global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-services'
    static_configs:
      - targets: ['backend:5000']
      - targets: ['frontend:80']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
